### PR TITLE
[SE-4288] Use service as a plugin app

### PR DESCRIPTION
**Pull request by gabor-boros**
Since the application could be installed as a plugin rather than a standalone service, this commit refactors the code to be able to install the install the app as an edX Django Plugin App.

The plugin configuration is intentionally not placed inside the settings module to avoid confusion and install of unrelated requirements like environ or dotent dependencies.

**Dependencies**: None

**Screenshots**: N/A

**Sandbox URL**: TBD - sandbox is being provisioned.

**Testing instructions**:

TBD

**Author notes and concerns**:

N/A

### CODE REVIEW

**Comment by fghaas** [comment]
Oh wow. I *really* appreciate the contribution, but I'm afraid that this PR is against the wrong repo. :( The correct code now lives in https://github.com/hastexo/webhook-receiver/ — we wanted to avoid any trademark issues, plus there already is a repo named https://github.com/edx/openedx-webhooks which does something completely different. And I just forgot to clean up this repo, i.e. set it read-only. I'm really, really sorry.

Would you mind taking a look to see if perhaps you can recreate the PR against the correct repo, with reasonable effort?

I'll swiftly add a note to this repo pointing people to the correct one.

**Comment by fghaas** [comment]
@gabor-boros Just checking: did you see the comment I added on 2021-04-08? :)

Can I help with the rebase?

**Comment by gabor-boros** [comment]
Hello @fghaas ,

Thank you for pinging me, I did not see the comment. I'll check that repo in a bit! Thank you again for notifying me!

**Comment by gabor-boros** [comment]
@fghaas Just checked it. As I can see the code is basically the same with some improvements and documentation fixes (like the client credentials part in the README), am I right?

If yes, I think I can open the PR against that repo today, but first I may need to do some changes on this branch (testing out some changes locally). When everything is working as expected, I'll open 2 PRs for the other repo depending on each other:

1. For being able to run as a edX django plugin app
2. For implementing a bulk "unenroll" listener (this will need some custom migration changes as well, so it will be bigger)

Is this something what sounds good for you too?

**Comment by fghaas** [comment]
@gabor-boros Yes that sounds perfect, thank you!

**Comment by fghaas** [comment]
Linking follow-up PR here so we have a cross-reference: https://github.com/hastexo/webhook-receiver/pull/2

@gabor-boros: Thanks for accommodating the repo change, and again sorry for the inconvenience. I'll archive this repo now to reduce confusion.

**Pull request closed without merging**
